before:
  hooks:
    - go mod download
builds:
- goos:
    - darwin
    - windows
    - linux
  goarch:
    - amd64
    - arm64
  ldflags: -X github.com/jaxxstorm/connectme/pkg/version.Version={{.Version}}
  binary: connectme
  main: ./cmd/connectme/main.go
archives:
- name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
  format_overrides:
    - goos: windows
      format: zip
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
changelog:
  skip: true
release:
  prerelease: auto
brews:
  - name: connectme
    tap:
      owner: jaxxstorm
      name: homebrew-tap
    commit_author:
      name: GitHub Actions
      email: bot@leebriggs.co.uk
    folder: Formula
    homepage: "https://leebriggs.co.uk"
    description: "Quickly connect to your cloud infrastructure"
    dependencies:
    - pulumi
scoop:
  url_template: "http://github.com/jaxxstorm/connectme/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  bucket:
    owner: jaxxstorm
    name: scoop-bucket
    branch: main
  commit_author:
    name: bot
    email: bot@leebriggs.co.uk
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: "https://leebriggs.co.uk/"
  description: "Quickly connect to your cloud infrastructure."

