permissions:
  contents: write

name: release
on:
  push:
    tags:
    - v*.*.*
    - '!v*.*.*-**'

jobs:    
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow clone
        run: git fetch --prune --unshallow
      - name: Install Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.x'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          args: release --clean --skip=validate
          version: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
