defaults:
  run:
    shell: bash
    working-directory: website

name: website
on:
  push:
    branches:
    - main
    paths:
    - website/**
    - .github/workflows/website.yml
jobs:    
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install npm packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Export
        run: npm run export
      - run: npm install -g wrangler
      - name: Publish
        run: wrangler pages publish --project-name=connecti ${{ github.workspace}}/website/out
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_TOKEN }}
