permissions:
  contents: write

name: release
on:
  push:
    branches:
    - main
    paths:
    - website
jobs:    
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
          workingDirectory: website/out
          command: pages publish --project-name=connecti
